#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : tcl
Version  : 8.6.10
Release  : 51
URL      : https://sourceforge.net/projects/tcl/files/Tcl/8.6.10/tcl8.6.10-src.tar.gz
Source0  : https://sourceforge.net/projects/tcl/files/Tcl/8.6.10/tcl8.6.10-src.tar.gz
Summary  : Tcl scripting language development environment
Group    : Development/Tools
License  : BSL-1.0 TCL
Requires: tcl-bin = %{version}-%{release}
Requires: tcl-lib = %{version}-%{release}
Requires: tcl-license = %{version}-%{release}
Requires: tcl-man = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-configure
BuildRequires : procps-ng
BuildRequires : sqlite-autoconf-dev
BuildRequires : tzdata
BuildRequires : zlib-dev
Patch1: build.patch

%description
The Tcl (Tool Command Language) provides a powerful platform for
creating integration applications that tie together diverse
applications, protocols, devices, and frameworks.  When paired with
the Tk toolkit, Tcl provides the fastest and most powerful way to
create GUI applications that run on PCs, Unix, and Mac OS X.  Tcl
can also be used for a variety of web-related tasks and for creating
powerful command languages for applications.

%package bin
Summary: bin components for the tcl package.
Group: Binaries
Requires: tcl-license = %{version}-%{release}

%description bin
bin components for the tcl package.


%package dev
Summary: dev components for the tcl package.
Group: Development
Requires: tcl-lib = %{version}-%{release}
Requires: tcl-bin = %{version}-%{release}
Provides: tcl-devel = %{version}-%{release}
Requires: tcl = %{version}-%{release}

%description dev
dev components for the tcl package.


%package lib
Summary: lib components for the tcl package.
Group: Libraries
Requires: tcl-license = %{version}-%{release}

%description lib
lib components for the tcl package.


%package license
Summary: license components for the tcl package.
Group: Default

%description license
license components for the tcl package.


%package man
Summary: man components for the tcl package.
Group: Default

%description man
man components for the tcl package.


%package staticdev
Summary: staticdev components for the tcl package.
Group: Default
Requires: tcl-dev = %{version}-%{release}

%description staticdev
staticdev components for the tcl package.


%prep
%setup -q -n tcl8.6.10
cd %{_builddir}/tcl8.6.10
%patch1 -p1

%build
## build_prepend content
export CFLAGS="$CFLAGS -O3"
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1605247376
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
pushd unix/
%configure  --enable-symbols
## make_prepend content
rm -rf %{_builddir}/tcl8.6.9/pkgs/sqlite3.25.3
## make_prepend end
make  %{?_smp_mflags}
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make -C unix test

%install
export SOURCE_DATE_EPOCH=1605247376
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/tcl
cp %{_builddir}/tcl8.6.10/compat/license.terms %{buildroot}/usr/share/package-licenses/tcl/4e9de7724f48cff19005312340a7f21ac741b94b
cp %{_builddir}/tcl8.6.10/compat/zlib/contrib/dotzlib/LICENSE_1_0.txt %{buildroot}/usr/share/package-licenses/tcl/892b34f7865d90a6f949f50d95e49625a10bc7f0
cp %{_builddir}/tcl8.6.10/doc/license.terms %{buildroot}/usr/share/package-licenses/tcl/4e9de7724f48cff19005312340a7f21ac741b94b
cp %{_builddir}/tcl8.6.10/library/license.terms %{buildroot}/usr/share/package-licenses/tcl/4e9de7724f48cff19005312340a7f21ac741b94b
cp %{_builddir}/tcl8.6.10/license.terms %{buildroot}/usr/share/package-licenses/tcl/4e9de7724f48cff19005312340a7f21ac741b94b
cp %{_builddir}/tcl8.6.10/macosx/license.terms %{buildroot}/usr/share/package-licenses/tcl/4e9de7724f48cff19005312340a7f21ac741b94b
cp %{_builddir}/tcl8.6.10/pkgs/itcl4.2.0/license.terms %{buildroot}/usr/share/package-licenses/tcl/0694c44c6528f38ba02518028ae540be0daffc82
cp %{_builddir}/tcl8.6.10/pkgs/tdbc1.1.1/license.terms %{buildroot}/usr/share/package-licenses/tcl/af1bb3f2eb2888c6a0cb73a32f12b2f599f9cd1f
cp %{_builddir}/tcl8.6.10/pkgs/tdbcmysql1.1.1/license.terms %{buildroot}/usr/share/package-licenses/tcl/af1bb3f2eb2888c6a0cb73a32f12b2f599f9cd1f
cp %{_builddir}/tcl8.6.10/pkgs/tdbcodbc1.1.1/license.terms %{buildroot}/usr/share/package-licenses/tcl/af1bb3f2eb2888c6a0cb73a32f12b2f599f9cd1f
cp %{_builddir}/tcl8.6.10/pkgs/tdbcpostgres1.1.1/license.terms %{buildroot}/usr/share/package-licenses/tcl/4cf449426b4a1f7696cb04e69ac100f262f5a715
cp %{_builddir}/tcl8.6.10/pkgs/tdbcsqlite3-1.1.1/license.terms %{buildroot}/usr/share/package-licenses/tcl/05c2120a6b8f992414f673c68a562cdf560f46e3
cp %{_builddir}/tcl8.6.10/pkgs/thread2.8.5/license.terms %{buildroot}/usr/share/package-licenses/tcl/44869749a0261aabc6d26adb33554b24f9b017c2
cp %{_builddir}/tcl8.6.10/tests/license.terms %{buildroot}/usr/share/package-licenses/tcl/4e9de7724f48cff19005312340a7f21ac741b94b
cp %{_builddir}/tcl8.6.10/win/license.terms %{buildroot}/usr/share/package-licenses/tcl/4e9de7724f48cff19005312340a7f21ac741b94b
pushd unix/
%make_install install-private-headers
popd
## Remove excluded files
rm -f %{buildroot}/usr/bin/sqlite3_analyzer
rm -f %{buildroot}/usr/share/man/man3/Thread.3
## install_append content
# build binary with funroll-loops
export CFLAGS="$CFLAGS -O3 -ffunction-sections -fno-semantic-interposition
-fopt-info-vec -flto"
export CXXFLAGS="$CXXFLAGS -O3 -ffunction-sections -fno-semantic-interposition
-fopt-info-vec"
pushd unix/
make V=1  %{?_smp_mflags}
%make_install install-binaries
rm -f %{buildroot}/usr/bin/sqlite3_analyzer
rm -f %{buildroot}/usr/share/man/man3/Thread.3
popd
ln -s /usr/bin/tclsh8.6 %{buildroot}/usr/bin/tclsh
ln -s libtcl8.6.so %{buildroot}/usr/lib64/libtcl.so
## install_append end

%files
%defattr(-,root,root,-)
/usr/lib/tcl8.6/auto.tcl
/usr/lib/tcl8.6/clock.tcl
/usr/lib/tcl8.6/encoding/ascii.enc
/usr/lib/tcl8.6/encoding/big5.enc
/usr/lib/tcl8.6/encoding/cp1250.enc
/usr/lib/tcl8.6/encoding/cp1251.enc
/usr/lib/tcl8.6/encoding/cp1252.enc
/usr/lib/tcl8.6/encoding/cp1253.enc
/usr/lib/tcl8.6/encoding/cp1254.enc
/usr/lib/tcl8.6/encoding/cp1255.enc
/usr/lib/tcl8.6/encoding/cp1256.enc
/usr/lib/tcl8.6/encoding/cp1257.enc
/usr/lib/tcl8.6/encoding/cp1258.enc
/usr/lib/tcl8.6/encoding/cp437.enc
/usr/lib/tcl8.6/encoding/cp737.enc
/usr/lib/tcl8.6/encoding/cp775.enc
/usr/lib/tcl8.6/encoding/cp850.enc
/usr/lib/tcl8.6/encoding/cp852.enc
/usr/lib/tcl8.6/encoding/cp855.enc
/usr/lib/tcl8.6/encoding/cp857.enc
/usr/lib/tcl8.6/encoding/cp860.enc
/usr/lib/tcl8.6/encoding/cp861.enc
/usr/lib/tcl8.6/encoding/cp862.enc
/usr/lib/tcl8.6/encoding/cp863.enc
/usr/lib/tcl8.6/encoding/cp864.enc
/usr/lib/tcl8.6/encoding/cp865.enc
/usr/lib/tcl8.6/encoding/cp866.enc
/usr/lib/tcl8.6/encoding/cp869.enc
/usr/lib/tcl8.6/encoding/cp874.enc
/usr/lib/tcl8.6/encoding/cp932.enc
/usr/lib/tcl8.6/encoding/cp936.enc
/usr/lib/tcl8.6/encoding/cp949.enc
/usr/lib/tcl8.6/encoding/cp950.enc
/usr/lib/tcl8.6/encoding/dingbats.enc
/usr/lib/tcl8.6/encoding/ebcdic.enc
/usr/lib/tcl8.6/encoding/euc-cn.enc
/usr/lib/tcl8.6/encoding/euc-jp.enc
/usr/lib/tcl8.6/encoding/euc-kr.enc
/usr/lib/tcl8.6/encoding/gb12345.enc
/usr/lib/tcl8.6/encoding/gb1988.enc
/usr/lib/tcl8.6/encoding/gb2312-raw.enc
/usr/lib/tcl8.6/encoding/gb2312.enc
/usr/lib/tcl8.6/encoding/iso2022-jp.enc
/usr/lib/tcl8.6/encoding/iso2022-kr.enc
/usr/lib/tcl8.6/encoding/iso2022.enc
/usr/lib/tcl8.6/encoding/iso8859-1.enc
/usr/lib/tcl8.6/encoding/iso8859-10.enc
/usr/lib/tcl8.6/encoding/iso8859-13.enc
/usr/lib/tcl8.6/encoding/iso8859-14.enc
/usr/lib/tcl8.6/encoding/iso8859-15.enc
/usr/lib/tcl8.6/encoding/iso8859-16.enc
/usr/lib/tcl8.6/encoding/iso8859-2.enc
/usr/lib/tcl8.6/encoding/iso8859-3.enc
/usr/lib/tcl8.6/encoding/iso8859-4.enc
/usr/lib/tcl8.6/encoding/iso8859-5.enc
/usr/lib/tcl8.6/encoding/iso8859-6.enc
/usr/lib/tcl8.6/encoding/iso8859-7.enc
/usr/lib/tcl8.6/encoding/iso8859-8.enc
/usr/lib/tcl8.6/encoding/iso8859-9.enc
/usr/lib/tcl8.6/encoding/jis0201.enc
/usr/lib/tcl8.6/encoding/jis0208.enc
/usr/lib/tcl8.6/encoding/jis0212.enc
/usr/lib/tcl8.6/encoding/koi8-r.enc
/usr/lib/tcl8.6/encoding/koi8-u.enc
/usr/lib/tcl8.6/encoding/ksc5601.enc
/usr/lib/tcl8.6/encoding/macCentEuro.enc
/usr/lib/tcl8.6/encoding/macCroatian.enc
/usr/lib/tcl8.6/encoding/macCyrillic.enc
/usr/lib/tcl8.6/encoding/macDingbats.enc
/usr/lib/tcl8.6/encoding/macGreek.enc
/usr/lib/tcl8.6/encoding/macIceland.enc
/usr/lib/tcl8.6/encoding/macJapan.enc
/usr/lib/tcl8.6/encoding/macRoman.enc
/usr/lib/tcl8.6/encoding/macRomania.enc
/usr/lib/tcl8.6/encoding/macThai.enc
/usr/lib/tcl8.6/encoding/macTurkish.enc
/usr/lib/tcl8.6/encoding/macUkraine.enc
/usr/lib/tcl8.6/encoding/shiftjis.enc
/usr/lib/tcl8.6/encoding/symbol.enc
/usr/lib/tcl8.6/encoding/tis-620.enc
/usr/lib/tcl8.6/history.tcl
/usr/lib/tcl8.6/http1.0/http.tcl
/usr/lib/tcl8.6/http1.0/pkgIndex.tcl
/usr/lib/tcl8.6/init.tcl
/usr/lib/tcl8.6/msgs/af.msg
/usr/lib/tcl8.6/msgs/af_za.msg
/usr/lib/tcl8.6/msgs/ar.msg
/usr/lib/tcl8.6/msgs/ar_in.msg
/usr/lib/tcl8.6/msgs/ar_jo.msg
/usr/lib/tcl8.6/msgs/ar_lb.msg
/usr/lib/tcl8.6/msgs/ar_sy.msg
/usr/lib/tcl8.6/msgs/be.msg
/usr/lib/tcl8.6/msgs/bg.msg
/usr/lib/tcl8.6/msgs/bn.msg
/usr/lib/tcl8.6/msgs/bn_in.msg
/usr/lib/tcl8.6/msgs/ca.msg
/usr/lib/tcl8.6/msgs/cs.msg
/usr/lib/tcl8.6/msgs/da.msg
/usr/lib/tcl8.6/msgs/de.msg
/usr/lib/tcl8.6/msgs/de_at.msg
/usr/lib/tcl8.6/msgs/de_be.msg
/usr/lib/tcl8.6/msgs/el.msg
/usr/lib/tcl8.6/msgs/en_au.msg
/usr/lib/tcl8.6/msgs/en_be.msg
/usr/lib/tcl8.6/msgs/en_bw.msg
/usr/lib/tcl8.6/msgs/en_ca.msg
/usr/lib/tcl8.6/msgs/en_gb.msg
/usr/lib/tcl8.6/msgs/en_hk.msg
/usr/lib/tcl8.6/msgs/en_ie.msg
/usr/lib/tcl8.6/msgs/en_in.msg
/usr/lib/tcl8.6/msgs/en_nz.msg
/usr/lib/tcl8.6/msgs/en_ph.msg
/usr/lib/tcl8.6/msgs/en_sg.msg
/usr/lib/tcl8.6/msgs/en_za.msg
/usr/lib/tcl8.6/msgs/en_zw.msg
/usr/lib/tcl8.6/msgs/eo.msg
/usr/lib/tcl8.6/msgs/es.msg
/usr/lib/tcl8.6/msgs/es_ar.msg
/usr/lib/tcl8.6/msgs/es_bo.msg
/usr/lib/tcl8.6/msgs/es_cl.msg
/usr/lib/tcl8.6/msgs/es_co.msg
/usr/lib/tcl8.6/msgs/es_cr.msg
/usr/lib/tcl8.6/msgs/es_do.msg
/usr/lib/tcl8.6/msgs/es_ec.msg
/usr/lib/tcl8.6/msgs/es_gt.msg
/usr/lib/tcl8.6/msgs/es_hn.msg
/usr/lib/tcl8.6/msgs/es_mx.msg
/usr/lib/tcl8.6/msgs/es_ni.msg
/usr/lib/tcl8.6/msgs/es_pa.msg
/usr/lib/tcl8.6/msgs/es_pe.msg
/usr/lib/tcl8.6/msgs/es_pr.msg
/usr/lib/tcl8.6/msgs/es_py.msg
/usr/lib/tcl8.6/msgs/es_sv.msg
/usr/lib/tcl8.6/msgs/es_uy.msg
/usr/lib/tcl8.6/msgs/es_ve.msg
/usr/lib/tcl8.6/msgs/et.msg
/usr/lib/tcl8.6/msgs/eu.msg
/usr/lib/tcl8.6/msgs/eu_es.msg
/usr/lib/tcl8.6/msgs/fa.msg
/usr/lib/tcl8.6/msgs/fa_in.msg
/usr/lib/tcl8.6/msgs/fa_ir.msg
/usr/lib/tcl8.6/msgs/fi.msg
/usr/lib/tcl8.6/msgs/fo.msg
/usr/lib/tcl8.6/msgs/fo_fo.msg
/usr/lib/tcl8.6/msgs/fr.msg
/usr/lib/tcl8.6/msgs/fr_be.msg
/usr/lib/tcl8.6/msgs/fr_ca.msg
/usr/lib/tcl8.6/msgs/fr_ch.msg
/usr/lib/tcl8.6/msgs/ga.msg
/usr/lib/tcl8.6/msgs/ga_ie.msg
/usr/lib/tcl8.6/msgs/gl.msg
/usr/lib/tcl8.6/msgs/gl_es.msg
/usr/lib/tcl8.6/msgs/gv.msg
/usr/lib/tcl8.6/msgs/gv_gb.msg
/usr/lib/tcl8.6/msgs/he.msg
/usr/lib/tcl8.6/msgs/hi.msg
/usr/lib/tcl8.6/msgs/hi_in.msg
/usr/lib/tcl8.6/msgs/hr.msg
/usr/lib/tcl8.6/msgs/hu.msg
/usr/lib/tcl8.6/msgs/id.msg
/usr/lib/tcl8.6/msgs/id_id.msg
/usr/lib/tcl8.6/msgs/is.msg
/usr/lib/tcl8.6/msgs/it.msg
/usr/lib/tcl8.6/msgs/it_ch.msg
/usr/lib/tcl8.6/msgs/ja.msg
/usr/lib/tcl8.6/msgs/kl.msg
/usr/lib/tcl8.6/msgs/kl_gl.msg
/usr/lib/tcl8.6/msgs/ko.msg
/usr/lib/tcl8.6/msgs/ko_kr.msg
/usr/lib/tcl8.6/msgs/kok.msg
/usr/lib/tcl8.6/msgs/kok_in.msg
/usr/lib/tcl8.6/msgs/kw.msg
/usr/lib/tcl8.6/msgs/kw_gb.msg
/usr/lib/tcl8.6/msgs/lt.msg
/usr/lib/tcl8.6/msgs/lv.msg
/usr/lib/tcl8.6/msgs/mk.msg
/usr/lib/tcl8.6/msgs/mr.msg
/usr/lib/tcl8.6/msgs/mr_in.msg
/usr/lib/tcl8.6/msgs/ms.msg
/usr/lib/tcl8.6/msgs/ms_my.msg
/usr/lib/tcl8.6/msgs/mt.msg
/usr/lib/tcl8.6/msgs/nb.msg
/usr/lib/tcl8.6/msgs/nl.msg
/usr/lib/tcl8.6/msgs/nl_be.msg
/usr/lib/tcl8.6/msgs/nn.msg
/usr/lib/tcl8.6/msgs/pl.msg
/usr/lib/tcl8.6/msgs/pt.msg
/usr/lib/tcl8.6/msgs/pt_br.msg
/usr/lib/tcl8.6/msgs/ro.msg
/usr/lib/tcl8.6/msgs/ru.msg
/usr/lib/tcl8.6/msgs/ru_ua.msg
/usr/lib/tcl8.6/msgs/sh.msg
/usr/lib/tcl8.6/msgs/sk.msg
/usr/lib/tcl8.6/msgs/sl.msg
/usr/lib/tcl8.6/msgs/sq.msg
/usr/lib/tcl8.6/msgs/sr.msg
/usr/lib/tcl8.6/msgs/sv.msg
/usr/lib/tcl8.6/msgs/sw.msg
/usr/lib/tcl8.6/msgs/ta.msg
/usr/lib/tcl8.6/msgs/ta_in.msg
/usr/lib/tcl8.6/msgs/te.msg
/usr/lib/tcl8.6/msgs/te_in.msg
/usr/lib/tcl8.6/msgs/th.msg
/usr/lib/tcl8.6/msgs/tr.msg
/usr/lib/tcl8.6/msgs/uk.msg
/usr/lib/tcl8.6/msgs/vi.msg
/usr/lib/tcl8.6/msgs/zh.msg
/usr/lib/tcl8.6/msgs/zh_cn.msg
/usr/lib/tcl8.6/msgs/zh_hk.msg
/usr/lib/tcl8.6/msgs/zh_sg.msg
/usr/lib/tcl8.6/msgs/zh_tw.msg
/usr/lib/tcl8.6/opt0.4/optparse.tcl
/usr/lib/tcl8.6/opt0.4/pkgIndex.tcl
/usr/lib/tcl8.6/package.tcl
/usr/lib/tcl8.6/parray.tcl
/usr/lib/tcl8.6/safe.tcl
/usr/lib/tcl8.6/tclAppInit.c
/usr/lib/tcl8.6/tclIndex
/usr/lib/tcl8.6/tm.tcl
/usr/lib/tcl8.6/word.tcl
/usr/lib/tcl8/8.4/platform-1.0.14.tm
/usr/lib/tcl8/8.4/platform/shell-1.1.4.tm
/usr/lib/tcl8/8.5/msgcat-1.6.1.tm
/usr/lib/tcl8/8.5/tcltest-2.5.1.tm
/usr/lib/tcl8/8.6/http-2.9.1.tm
/usr/lib64/itcl4.2.0/itcl.tcl
/usr/lib64/itcl4.2.0/itclConfig.sh
/usr/lib64/itcl4.2.0/itclHullCmds.tcl
/usr/lib64/itcl4.2.0/itclWidget.tcl
/usr/lib64/itcl4.2.0/libitclstub4.2.0.a
/usr/lib64/itcl4.2.0/pkgIndex.tcl
/usr/lib64/sqlite3.30.1.2/pkgIndex.tcl
/usr/lib64/tcl8/8.6/tdbc/sqlite3-1.1.1.tm
/usr/lib64/tclConfig.sh
/usr/lib64/tclooConfig.sh
/usr/lib64/tdbc1.1.1/libtdbcstub1.1.1.a
/usr/lib64/tdbc1.1.1/pkgIndex.tcl
/usr/lib64/tdbc1.1.1/tdbc.tcl
/usr/lib64/tdbc1.1.1/tdbcConfig.sh
/usr/lib64/tdbcmysql1.1.1/pkgIndex.tcl
/usr/lib64/tdbcmysql1.1.1/tdbcmysql.tcl
/usr/lib64/tdbcodbc1.1.1/pkgIndex.tcl
/usr/lib64/tdbcodbc1.1.1/tdbcodbc.tcl
/usr/lib64/tdbcpostgres1.1.1/pkgIndex.tcl
/usr/lib64/tdbcpostgres1.1.1/tdbcpostgres.tcl
/usr/lib64/thread2.8.5/pkgIndex.tcl
/usr/lib64/thread2.8.5/ttrace.tcl

%files bin
%defattr(-,root,root,-)
/usr/bin/tclsh
/usr/bin/tclsh8.6

%files dev
%defattr(-,root,root,-)
/usr/include/fakemysql.h
/usr/include/fakepq.h
/usr/include/fakesql.h
/usr/include/itcl.h
/usr/include/itcl2TclOO.h
/usr/include/itclDecls.h
/usr/include/itclInt.h
/usr/include/itclIntDecls.h
/usr/include/itclMigrate2TclCore.h
/usr/include/itclTclIntStubsFcn.h
/usr/include/mysqlStubs.h
/usr/include/odbcStubs.h
/usr/include/pqStubs.h
/usr/include/tcl.h
/usr/include/tclDecls.h
/usr/include/tclInt.h
/usr/include/tclIntDecls.h
/usr/include/tclIntPlatDecls.h
/usr/include/tclOO.h
/usr/include/tclOODecls.h
/usr/include/tclOOInt.h
/usr/include/tclOOIntDecls.h
/usr/include/tclPlatDecls.h
/usr/include/tclPort.h
/usr/include/tclThread.h
/usr/include/tclTomMath.h
/usr/include/tclTomMathDecls.h
/usr/include/tclUnixPort.h
/usr/include/tdbc.h
/usr/include/tdbcDecls.h
/usr/include/tdbcInt.h
/usr/lib64/pkgconfig/tcl.pc
/usr/share/man/man3/DString.3
/usr/share/man/man3/Notifier.3
/usr/share/man/man3/RegExp.3
/usr/share/man/man3/TCL_MEM_DEBUG.3
/usr/share/man/man3/Tcl_Access.3
/usr/share/man/man3/Tcl_AddErrorInfo.3
/usr/share/man/man3/Tcl_AddObjErrorInfo.3
/usr/share/man/man3/Tcl_AlertNotifier.3
/usr/share/man/man3/Tcl_Alloc.3
/usr/share/man/man3/Tcl_AllocStatBuf.3
/usr/share/man/man3/Tcl_AllowExceptions.3
/usr/share/man/man3/Tcl_AppInit.3
/usr/share/man/man3/Tcl_AppendAllObjTypes.3
/usr/share/man/man3/Tcl_AppendElement.3
/usr/share/man/man3/Tcl_AppendExportList.3
/usr/share/man/man3/Tcl_AppendFormatToObj.3
/usr/share/man/man3/Tcl_AppendLimitedToObj.3
/usr/share/man/man3/Tcl_AppendObjToErrorInfo.3
/usr/share/man/man3/Tcl_AppendObjToObj.3
/usr/share/man/man3/Tcl_AppendPrintfToObj.3
/usr/share/man/man3/Tcl_AppendResult.3
/usr/share/man/man3/Tcl_AppendResultVA.3
/usr/share/man/man3/Tcl_AppendStringsToObj.3
/usr/share/man/man3/Tcl_AppendStringsToObjVA.3
/usr/share/man/man3/Tcl_AppendToObj.3
/usr/share/man/man3/Tcl_AppendUnicodeToObj.3
/usr/share/man/man3/Tcl_AsyncCreate.3
/usr/share/man/man3/Tcl_AsyncDelete.3
/usr/share/man/man3/Tcl_AsyncInvoke.3
/usr/share/man/man3/Tcl_AsyncMark.3
/usr/share/man/man3/Tcl_AsyncReady.3
/usr/share/man/man3/Tcl_AttemptAlloc.3
/usr/share/man/man3/Tcl_AttemptRealloc.3
/usr/share/man/man3/Tcl_AttemptSetObjLength.3
/usr/share/man/man3/Tcl_BackgroundError.3
/usr/share/man/man3/Tcl_BackgroundException.3
/usr/share/man/man3/Tcl_Backslash.3
/usr/share/man/man3/Tcl_BadChannelOption.3
/usr/share/man/man3/Tcl_CallWhenDeleted.3
/usr/share/man/man3/Tcl_CancelEval.3
/usr/share/man/man3/Tcl_CancelIdleCall.3
/usr/share/man/man3/Tcl_Canceled.3
/usr/share/man/man3/Tcl_ChannelBlockModeProc.3
/usr/share/man/man3/Tcl_ChannelBuffered.3
/usr/share/man/man3/Tcl_ChannelClose2Proc.3
/usr/share/man/man3/Tcl_ChannelCloseProc.3
/usr/share/man/man3/Tcl_ChannelFlushProc.3
/usr/share/man/man3/Tcl_ChannelGetHandleProc.3
/usr/share/man/man3/Tcl_ChannelGetOptionProc.3
/usr/share/man/man3/Tcl_ChannelHandlerProc.3
/usr/share/man/man3/Tcl_ChannelInputProc.3
/usr/share/man/man3/Tcl_ChannelName.3
/usr/share/man/man3/Tcl_ChannelOutputProc.3
/usr/share/man/man3/Tcl_ChannelSeekProc.3
/usr/share/man/man3/Tcl_ChannelSetOptionProc.3
/usr/share/man/man3/Tcl_ChannelThreadActionProc.3
/usr/share/man/man3/Tcl_ChannelTruncateProc.3
/usr/share/man/man3/Tcl_ChannelVersion.3
/usr/share/man/man3/Tcl_ChannelWatchProc.3
/usr/share/man/man3/Tcl_ChannelWideSeekProc.3
/usr/share/man/man3/Tcl_Chdir.3
/usr/share/man/man3/Tcl_ClassGetMetadata.3
/usr/share/man/man3/Tcl_ClassSetConstructor.3
/usr/share/man/man3/Tcl_ClassSetDestructor.3
/usr/share/man/man3/Tcl_ClassSetMetadata.3
/usr/share/man/man3/Tcl_ClearChannelHandlers.3
/usr/share/man/man3/Tcl_Close.3
/usr/share/man/man3/Tcl_CommandComplete.3
/usr/share/man/man3/Tcl_CommandTraceInfo.3
/usr/share/man/man3/Tcl_Concat.3
/usr/share/man/man3/Tcl_ConcatObj.3
/usr/share/man/man3/Tcl_ConditionFinalize.3
/usr/share/man/man3/Tcl_ConditionNotify.3
/usr/share/man/man3/Tcl_ConditionWait.3
/usr/share/man/man3/Tcl_ConvertCountedElement.3
/usr/share/man/man3/Tcl_ConvertElement.3
/usr/share/man/man3/Tcl_ConvertToType.3
/usr/share/man/man3/Tcl_CopyObjectInstance.3
/usr/share/man/man3/Tcl_CreateAlias.3
/usr/share/man/man3/Tcl_CreateAliasObj.3
/usr/share/man/man3/Tcl_CreateChannel.3
/usr/share/man/man3/Tcl_CreateChannelHandler.3
/usr/share/man/man3/Tcl_CreateCloseHandler.3
/usr/share/man/man3/Tcl_CreateCommand.3
/usr/share/man/man3/Tcl_CreateEncoding.3
/usr/share/man/man3/Tcl_CreateEnsemble.3
/usr/share/man/man3/Tcl_CreateEventSource.3
/usr/share/man/man3/Tcl_CreateExitHandler.3
/usr/share/man/man3/Tcl_CreateFileHandler.3
/usr/share/man/man3/Tcl_CreateHashEntry.3
/usr/share/man/man3/Tcl_CreateInterp.3
/usr/share/man/man3/Tcl_CreateMathFunc.3
/usr/share/man/man3/Tcl_CreateNamespace.3
/usr/share/man/man3/Tcl_CreateObjCommand.3
/usr/share/man/man3/Tcl_CreateObjTrace.3
/usr/share/man/man3/Tcl_CreateSlave.3
/usr/share/man/man3/Tcl_CreateThread.3
/usr/share/man/man3/Tcl_CreateThreadExitHandler.3
/usr/share/man/man3/Tcl_CreateTimerHandler.3
/usr/share/man/man3/Tcl_CreateTrace.3
/usr/share/man/man3/Tcl_CutChannel.3
/usr/share/man/man3/Tcl_DStringAppend.3
/usr/share/man/man3/Tcl_DStringAppendElement.3
/usr/share/man/man3/Tcl_DStringEndSublist.3
/usr/share/man/man3/Tcl_DStringFree.3
/usr/share/man/man3/Tcl_DStringGetResult.3
/usr/share/man/man3/Tcl_DStringInit.3
/usr/share/man/man3/Tcl_DStringLength.3
/usr/share/man/man3/Tcl_DStringResult.3
/usr/share/man/man3/Tcl_DStringSetLength.3
/usr/share/man/man3/Tcl_DStringStartSublist.3
/usr/share/man/man3/Tcl_DStringTrunc.3
/usr/share/man/man3/Tcl_DStringValue.3
/usr/share/man/man3/Tcl_DecrRefCount.3
/usr/share/man/man3/Tcl_DeleteAssocData.3
/usr/share/man/man3/Tcl_DeleteChannelHandler.3
/usr/share/man/man3/Tcl_DeleteCloseHandler.3
/usr/share/man/man3/Tcl_DeleteCommand.3
/usr/share/man/man3/Tcl_DeleteCommandFromToken.3
/usr/share/man/man3/Tcl_DeleteEventSource.3
/usr/share/man/man3/Tcl_DeleteEvents.3
/usr/share/man/man3/Tcl_DeleteExitHandler.3
/usr/share/man/man3/Tcl_DeleteFileHandler.3
/usr/share/man/man3/Tcl_DeleteHashEntry.3
/usr/share/man/man3/Tcl_DeleteHashTable.3
/usr/share/man/man3/Tcl_DeleteInterp.3
/usr/share/man/man3/Tcl_DeleteNamespace.3
/usr/share/man/man3/Tcl_DeleteThreadExitHandler.3
/usr/share/man/man3/Tcl_DeleteTimerHandler.3
/usr/share/man/man3/Tcl_DeleteTrace.3
/usr/share/man/man3/Tcl_DetachChannel.3
/usr/share/man/man3/Tcl_DetachPids.3
/usr/share/man/man3/Tcl_DictObjDone.3
/usr/share/man/man3/Tcl_DictObjFirst.3
/usr/share/man/man3/Tcl_DictObjGet.3
/usr/share/man/man3/Tcl_DictObjNext.3
/usr/share/man/man3/Tcl_DictObjPut.3
/usr/share/man/man3/Tcl_DictObjPutKeyList.3
/usr/share/man/man3/Tcl_DictObjRemove.3
/usr/share/man/man3/Tcl_DictObjRemoveKeyList.3
/usr/share/man/man3/Tcl_DictObjSize.3
/usr/share/man/man3/Tcl_DiscardInterpState.3
/usr/share/man/man3/Tcl_DiscardResult.3
/usr/share/man/man3/Tcl_DoOneEvent.3
/usr/share/man/man3/Tcl_DoWhenIdle.3
/usr/share/man/man3/Tcl_DontCallWhenDeleted.3
/usr/share/man/man3/Tcl_DumpActiveMemory.3
/usr/share/man/man3/Tcl_DuplicateObj.3
/usr/share/man/man3/Tcl_Eof.3
/usr/share/man/man3/Tcl_ErrnoId.3
/usr/share/man/man3/Tcl_ErrnoMsg.3
/usr/share/man/man3/Tcl_Eval.3
/usr/share/man/man3/Tcl_EvalEx.3
/usr/share/man/man3/Tcl_EvalFile.3
/usr/share/man/man3/Tcl_EvalObjEx.3
/usr/share/man/man3/Tcl_EvalObjv.3
/usr/share/man/man3/Tcl_EvalTokens.3
/usr/share/man/man3/Tcl_EvalTokensStandard.3
/usr/share/man/man3/Tcl_EventuallyFree.3
/usr/share/man/man3/Tcl_Exit.3
/usr/share/man/man3/Tcl_ExitThread.3
/usr/share/man/man3/Tcl_Export.3
/usr/share/man/man3/Tcl_ExposeCommand.3
/usr/share/man/man3/Tcl_ExprBoolean.3
/usr/share/man/man3/Tcl_ExprBooleanObj.3
/usr/share/man/man3/Tcl_ExprDouble.3
/usr/share/man/man3/Tcl_ExprDoubleObj.3
/usr/share/man/man3/Tcl_ExprLong.3
/usr/share/man/man3/Tcl_ExprLongObj.3
/usr/share/man/man3/Tcl_ExprObj.3
/usr/share/man/man3/Tcl_ExprString.3
/usr/share/man/man3/Tcl_ExternalToUtf.3
/usr/share/man/man3/Tcl_ExternalToUtfDString.3
/usr/share/man/man3/Tcl_FSAccess.3
/usr/share/man/man3/Tcl_FSChdir.3
/usr/share/man/man3/Tcl_FSConvertToPathType.3
/usr/share/man/man3/Tcl_FSCopyDirectory.3
/usr/share/man/man3/Tcl_FSCopyFile.3
/usr/share/man/man3/Tcl_FSCreateDirectory.3
/usr/share/man/man3/Tcl_FSData.3
/usr/share/man/man3/Tcl_FSDeleteFile.3
/usr/share/man/man3/Tcl_FSEqualPaths.3
/usr/share/man/man3/Tcl_FSEvalFile.3
/usr/share/man/man3/Tcl_FSEvalFileEx.3
/usr/share/man/man3/Tcl_FSFileAttrStrings.3
/usr/share/man/man3/Tcl_FSFileAttrsGet.3
/usr/share/man/man3/Tcl_FSFileAttrsSet.3
/usr/share/man/man3/Tcl_FSFileSystemInfo.3
/usr/share/man/man3/Tcl_FSGetCwd.3
/usr/share/man/man3/Tcl_FSGetFileSystemForPath.3
/usr/share/man/man3/Tcl_FSGetInternalRep.3
/usr/share/man/man3/Tcl_FSGetNativePath.3
/usr/share/man/man3/Tcl_FSGetNormalizedPath.3
/usr/share/man/man3/Tcl_FSGetPathType.3
/usr/share/man/man3/Tcl_FSGetTranslatedPath.3
/usr/share/man/man3/Tcl_FSGetTranslatedStringPath.3
/usr/share/man/man3/Tcl_FSJoinPath.3
/usr/share/man/man3/Tcl_FSJoinToPath.3
/usr/share/man/man3/Tcl_FSLink.3
/usr/share/man/man3/Tcl_FSListVolumes.3
/usr/share/man/man3/Tcl_FSLoadFile.3
/usr/share/man/man3/Tcl_FSLstat.3
/usr/share/man/man3/Tcl_FSMatchInDirectory.3
/usr/share/man/man3/Tcl_FSMountsChanged.3
/usr/share/man/man3/Tcl_FSNewNativePath.3
/usr/share/man/man3/Tcl_FSOpenFileChannel.3
/usr/share/man/man3/Tcl_FSPathSeparator.3
/usr/share/man/man3/Tcl_FSRegister.3
/usr/share/man/man3/Tcl_FSRemoveDirectory.3
/usr/share/man/man3/Tcl_FSRenameFile.3
/usr/share/man/man3/Tcl_FSSplitPath.3
/usr/share/man/man3/Tcl_FSStat.3
/usr/share/man/man3/Tcl_FSUnloadFile.3
/usr/share/man/man3/Tcl_FSUnregister.3
/usr/share/man/man3/Tcl_FSUtime.3
/usr/share/man/man3/Tcl_Finalize.3
/usr/share/man/man3/Tcl_FinalizeNotifier.3
/usr/share/man/man3/Tcl_FinalizeThread.3
/usr/share/man/man3/Tcl_FindCommand.3
/usr/share/man/man3/Tcl_FindEnsemble.3
/usr/share/man/man3/Tcl_FindExecutable.3
/usr/share/man/man3/Tcl_FindHashEntry.3
/usr/share/man/man3/Tcl_FindNamespace.3
/usr/share/man/man3/Tcl_FindSymbol.3
/usr/share/man/man3/Tcl_FirstHashEntry.3
/usr/share/man/man3/Tcl_Flush.3
/usr/share/man/man3/Tcl_ForgetImport.3
/usr/share/man/man3/Tcl_Format.3
/usr/share/man/man3/Tcl_Free.3
/usr/share/man/man3/Tcl_FreeEncoding.3
/usr/share/man/man3/Tcl_FreeParse.3
/usr/share/man/man3/Tcl_FreeResult.3
/usr/share/man/man3/Tcl_GetAccessTimeFromStat.3
/usr/share/man/man3/Tcl_GetAlias.3
/usr/share/man/man3/Tcl_GetAliasObj.3
/usr/share/man/man3/Tcl_GetAssocData.3
/usr/share/man/man3/Tcl_GetBignumFromObj.3
/usr/share/man/man3/Tcl_GetBlockSizeFromStat.3
/usr/share/man/man3/Tcl_GetBlocksFromStat.3
/usr/share/man/man3/Tcl_GetBoolean.3
/usr/share/man/man3/Tcl_GetBooleanFromObj.3
/usr/share/man/man3/Tcl_GetByteArrayFromObj.3
/usr/share/man/man3/Tcl_GetChangeTimeFromStat.3
/usr/share/man/man3/Tcl_GetChannel.3
/usr/share/man/man3/Tcl_GetChannelBufferSize.3
/usr/share/man/man3/Tcl_GetChannelError.3
/usr/share/man/man3/Tcl_GetChannelErrorInterp.3
/usr/share/man/man3/Tcl_GetChannelHandle.3
/usr/share/man/man3/Tcl_GetChannelInstanceData.3
/usr/share/man/man3/Tcl_GetChannelMode.3
/usr/share/man/man3/Tcl_GetChannelName.3
/usr/share/man/man3/Tcl_GetChannelNames.3
/usr/share/man/man3/Tcl_GetChannelNamesEx.3
/usr/share/man/man3/Tcl_GetChannelOption.3
/usr/share/man/man3/Tcl_GetChannelThread.3
/usr/share/man/man3/Tcl_GetChannelType.3
/usr/share/man/man3/Tcl_GetCharLength.3
/usr/share/man/man3/Tcl_GetClassAsObject.3
/usr/share/man/man3/Tcl_GetCommandFromObj.3
/usr/share/man/man3/Tcl_GetCommandFullName.3
/usr/share/man/man3/Tcl_GetCommandInfo.3
/usr/share/man/man3/Tcl_GetCommandInfoFromToken.3
/usr/share/man/man3/Tcl_GetCommandName.3
/usr/share/man/man3/Tcl_GetCurrentNamespace.3
/usr/share/man/man3/Tcl_GetCurrentThread.3
/usr/share/man/man3/Tcl_GetCwd.3
/usr/share/man/man3/Tcl_GetDefaultEncodingDir.3
/usr/share/man/man3/Tcl_GetDeviceTypeFromStat.3
/usr/share/man/man3/Tcl_GetDouble.3
/usr/share/man/man3/Tcl_GetDoubleFromObj.3
/usr/share/man/man3/Tcl_GetEncoding.3
/usr/share/man/man3/Tcl_GetEncodingFromObj.3
/usr/share/man/man3/Tcl_GetEncodingName.3
/usr/share/man/man3/Tcl_GetEncodingNameFromEnvironment.3
/usr/share/man/man3/Tcl_GetEncodingNames.3
/usr/share/man/man3/Tcl_GetEncodingSearchPath.3
/usr/share/man/man3/Tcl_GetEnsembleFlags.3
/usr/share/man/man3/Tcl_GetEnsembleMappingDict.3
/usr/share/man/man3/Tcl_GetEnsembleNamespace.3
/usr/share/man/man3/Tcl_GetEnsembleParameterList.3
/usr/share/man/man3/Tcl_GetEnsembleSubcommandList.3
/usr/share/man/man3/Tcl_GetEnsembleUnknownHandler.3
/usr/share/man/man3/Tcl_GetErrno.3
/usr/share/man/man3/Tcl_GetErrorLine.3
/usr/share/man/man3/Tcl_GetFSDeviceFromStat.3
/usr/share/man/man3/Tcl_GetFSInodeFromStat.3
/usr/share/man/man3/Tcl_GetGlobalNamespace.3
/usr/share/man/man3/Tcl_GetGroupIdFromStat.3
/usr/share/man/man3/Tcl_GetHashKey.3
/usr/share/man/man3/Tcl_GetHashValue.3
/usr/share/man/man3/Tcl_GetHostName.3
/usr/share/man/man3/Tcl_GetIndexFromObj.3
/usr/share/man/man3/Tcl_GetIndexFromObjStruct.3
/usr/share/man/man3/Tcl_GetInt.3
/usr/share/man/man3/Tcl_GetIntFromObj.3
/usr/share/man/man3/Tcl_GetInterpPath.3
/usr/share/man/man3/Tcl_GetLinkCountFromStat.3
/usr/share/man/man3/Tcl_GetLongFromObj.3
/usr/share/man/man3/Tcl_GetMaster.3
/usr/share/man/man3/Tcl_GetMathFuncInfo.3
/usr/share/man/man3/Tcl_GetModeFromStat.3
/usr/share/man/man3/Tcl_GetModificationTimeFromStat.3
/usr/share/man/man3/Tcl_GetNameOfExecutable.3
/usr/share/man/man3/Tcl_GetNamespaceUnknownHandler.3
/usr/share/man/man3/Tcl_GetObjResult.3
/usr/share/man/man3/Tcl_GetObjType.3
/usr/share/man/man3/Tcl_GetObjectAsClass.3
/usr/share/man/man3/Tcl_GetObjectCommand.3
/usr/share/man/man3/Tcl_GetObjectFromObj.3
/usr/share/man/man3/Tcl_GetObjectName.3
/usr/share/man/man3/Tcl_GetObjectNamespace.3
/usr/share/man/man3/Tcl_GetOpenFile.3
/usr/share/man/man3/Tcl_GetPathType.3
/usr/share/man/man3/Tcl_GetRange.3
/usr/share/man/man3/Tcl_GetRegExpFromObj.3
/usr/share/man/man3/Tcl_GetReturnOptions.3
/usr/share/man/man3/Tcl_GetServiceMode.3
/usr/share/man/man3/Tcl_GetSizeFromStat.3
/usr/share/man/man3/Tcl_GetSlave.3
/usr/share/man/man3/Tcl_GetStackedChannel.3
/usr/share/man/man3/Tcl_GetStartupScript.3
/usr/share/man/man3/Tcl_GetStdChannel.3
/usr/share/man/man3/Tcl_GetString.3
/usr/share/man/man3/Tcl_GetStringFromObj.3
/usr/share/man/man3/Tcl_GetStringResult.3
/usr/share/man/man3/Tcl_GetThreadData.3
/usr/share/man/man3/Tcl_GetTime.3
/usr/share/man/man3/Tcl_GetTopChannel.3
/usr/share/man/man3/Tcl_GetUniChar.3
/usr/share/man/man3/Tcl_GetUnicode.3
/usr/share/man/man3/Tcl_GetUnicodeFromObj.3
/usr/share/man/man3/Tcl_GetUserIdFromStat.3
/usr/share/man/man3/Tcl_GetVar.3
/usr/share/man/man3/Tcl_GetVar2.3
/usr/share/man/man3/Tcl_GetVar2Ex.3
/usr/share/man/man3/Tcl_GetVersion.3
/usr/share/man/man3/Tcl_GetWideIntFromObj.3
/usr/share/man/man3/Tcl_Gets.3
/usr/share/man/man3/Tcl_GetsObj.3
/usr/share/man/man3/Tcl_GlobalEval.3
/usr/share/man/man3/Tcl_GlobalEvalObj.3
/usr/share/man/man3/Tcl_HashStats.3
/usr/share/man/man3/Tcl_HideCommand.3
/usr/share/man/man3/Tcl_Import.3
/usr/share/man/man3/Tcl_IncrRefCount.3
/usr/share/man/man3/Tcl_Init.3
/usr/share/man/man3/Tcl_InitCustomHashTable.3
/usr/share/man/man3/Tcl_InitHashTable.3
/usr/share/man/man3/Tcl_InitMemory.3
/usr/share/man/man3/Tcl_InitNotifier.3
/usr/share/man/man3/Tcl_InitObjHashTable.3
/usr/share/man/man3/Tcl_InitStubs.3
/usr/share/man/man3/Tcl_InputBlocked.3
/usr/share/man/man3/Tcl_InputBuffered.3
/usr/share/man/man3/Tcl_Interp.3
/usr/share/man/man3/Tcl_InterpActive.3
/usr/share/man/man3/Tcl_InterpDeleted.3
/usr/share/man/man3/Tcl_InvalidateStringRep.3
/usr/share/man/man3/Tcl_IsChannelExisting.3
/usr/share/man/man3/Tcl_IsChannelRegistered.3
/usr/share/man/man3/Tcl_IsChannelShared.3
/usr/share/man/man3/Tcl_IsEnsemble.3
/usr/share/man/man3/Tcl_IsSafe.3
/usr/share/man/man3/Tcl_IsShared.3
/usr/share/man/man3/Tcl_IsStandardChannel.3
/usr/share/man/man3/Tcl_JoinPath.3
/usr/share/man/man3/Tcl_JoinThread.3
/usr/share/man/man3/Tcl_LimitAddHandler.3
/usr/share/man/man3/Tcl_LimitCheck.3
/usr/share/man/man3/Tcl_LimitExceeded.3
/usr/share/man/man3/Tcl_LimitGetCommands.3
/usr/share/man/man3/Tcl_LimitGetGranularity.3
/usr/share/man/man3/Tcl_LimitGetTime.3
/usr/share/man/man3/Tcl_LimitReady.3
/usr/share/man/man3/Tcl_LimitRemoveHandler.3
/usr/share/man/man3/Tcl_LimitSetCommands.3
/usr/share/man/man3/Tcl_LimitSetGranularity.3
/usr/share/man/man3/Tcl_LimitSetTime.3
/usr/share/man/man3/Tcl_LimitTypeEnabled.3
/usr/share/man/man3/Tcl_LimitTypeExceeded.3
/usr/share/man/man3/Tcl_LimitTypeReset.3
/usr/share/man/man3/Tcl_LimitTypeSet.3
/usr/share/man/man3/Tcl_LinkVar.3
/usr/share/man/man3/Tcl_ListMathFuncs.3
/usr/share/man/man3/Tcl_ListObjAppendElement.3
/usr/share/man/man3/Tcl_ListObjAppendList.3
/usr/share/man/man3/Tcl_ListObjGetElements.3
/usr/share/man/man3/Tcl_ListObjIndex.3
/usr/share/man/man3/Tcl_ListObjLength.3
/usr/share/man/man3/Tcl_ListObjReplace.3
/usr/share/man/man3/Tcl_LoadFile.3
/usr/share/man/man3/Tcl_LogCommandInfo.3
/usr/share/man/man3/Tcl_Main.3
/usr/share/man/man3/Tcl_MakeFileChannel.3
/usr/share/man/man3/Tcl_MakeSafe.3
/usr/share/man/man3/Tcl_MakeTcpClientChannel.3
/usr/share/man/man3/Tcl_Merge.3
/usr/share/man/man3/Tcl_MethodDeclarerClass.3
/usr/share/man/man3/Tcl_MethodDeclarerObject.3
/usr/share/man/man3/Tcl_MethodIsPublic.3
/usr/share/man/man3/Tcl_MethodIsType.3
/usr/share/man/man3/Tcl_MethodName.3
/usr/share/man/man3/Tcl_MutexFinalize.3
/usr/share/man/man3/Tcl_MutexLock.3
/usr/share/man/man3/Tcl_MutexUnlock.3
/usr/share/man/man3/Tcl_NRAddCallback.3
/usr/share/man/man3/Tcl_NRCallObjProc.3
/usr/share/man/man3/Tcl_NRCmdSwap.3
/usr/share/man/man3/Tcl_NRCreateCommand.3
/usr/share/man/man3/Tcl_NREvalObj.3
/usr/share/man/man3/Tcl_NREvalObjv.3
/usr/share/man/man3/Tcl_NRExprObj.3
/usr/share/man/man3/Tcl_NewBignumObj.3
/usr/share/man/man3/Tcl_NewBooleanObj.3
/usr/share/man/man3/Tcl_NewByteArrayObj.3
/usr/share/man/man3/Tcl_NewDictObj.3
/usr/share/man/man3/Tcl_NewDoubleObj.3
/usr/share/man/man3/Tcl_NewInstanceMethod.3
/usr/share/man/man3/Tcl_NewIntObj.3
/usr/share/man/man3/Tcl_NewListObj.3
/usr/share/man/man3/Tcl_NewLongObj.3
/usr/share/man/man3/Tcl_NewMethod.3
/usr/share/man/man3/Tcl_NewObj.3
/usr/share/man/man3/Tcl_NewObjectInstance.3
/usr/share/man/man3/Tcl_NewStringObj.3
/usr/share/man/man3/Tcl_NewUnicodeObj.3
/usr/share/man/man3/Tcl_NewWideIntObj.3
/usr/share/man/man3/Tcl_NextHashEntry.3
/usr/share/man/man3/Tcl_NotifyChannel.3
/usr/share/man/man3/Tcl_NumUtfChars.3
/usr/share/man/man3/Tcl_OOInitStubs.3
/usr/share/man/man3/Tcl_ObjGetVar2.3
/usr/share/man/man3/Tcl_ObjPrintf.3
/usr/share/man/man3/Tcl_ObjSetVar2.3
/usr/share/man/man3/Tcl_ObjectContextInvokeNext.3
/usr/share/man/man3/Tcl_ObjectContextIsFiltering.3
/usr/share/man/man3/Tcl_ObjectContextMethod.3
/usr/share/man/man3/Tcl_ObjectContextObject.3
/usr/share/man/man3/Tcl_ObjectContextSkippedArgs.3
/usr/share/man/man3/Tcl_ObjectDeleted.3
/usr/share/man/man3/Tcl_ObjectGetMetadata.3
/usr/share/man/man3/Tcl_ObjectGetMethodNameMapper.3
/usr/share/man/man3/Tcl_ObjectSetMetadata.3
/usr/share/man/man3/Tcl_ObjectSetMethodNameMapper.3
/usr/share/man/man3/Tcl_OpenCommandChannel.3
/usr/share/man/man3/Tcl_OpenFileChannel.3
/usr/share/man/man3/Tcl_OpenTcpClient.3
/usr/share/man/man3/Tcl_OpenTcpServer.3
/usr/share/man/man3/Tcl_OutputBuffered.3
/usr/share/man/man3/Tcl_Panic.3
/usr/share/man/man3/Tcl_PanicVA.3
/usr/share/man/man3/Tcl_ParseArgsObjv.3
/usr/share/man/man3/Tcl_ParseBraces.3
/usr/share/man/man3/Tcl_ParseCommand.3
/usr/share/man/man3/Tcl_ParseExpr.3
/usr/share/man/man3/Tcl_ParseQuotedString.3
/usr/share/man/man3/Tcl_ParseVar.3
/usr/share/man/man3/Tcl_ParseVarName.3
/usr/share/man/man3/Tcl_PkgPresent.3
/usr/share/man/man3/Tcl_PkgPresentEx.3
/usr/share/man/man3/Tcl_PkgProvide.3
/usr/share/man/man3/Tcl_PkgProvideEx.3
/usr/share/man/man3/Tcl_PkgRequire.3
/usr/share/man/man3/Tcl_PkgRequireEx.3
/usr/share/man/man3/Tcl_PkgRequireProc.3
/usr/share/man/man3/Tcl_PosixError.3
/usr/share/man/man3/Tcl_Preserve.3
/usr/share/man/man3/Tcl_PrintDouble.3
/usr/share/man/man3/Tcl_PutEnv.3
/usr/share/man/man3/Tcl_QueryTimeProc.3
/usr/share/man/man3/Tcl_QueueEvent.3
/usr/share/man/man3/Tcl_Read.3
/usr/share/man/man3/Tcl_ReadChars.3
/usr/share/man/man3/Tcl_ReadRaw.3
/usr/share/man/man3/Tcl_Realloc.3
/usr/share/man/man3/Tcl_ReapDetachedProcs.3
/usr/share/man/man3/Tcl_RecordAndEval.3
/usr/share/man/man3/Tcl_RecordAndEvalObj.3
/usr/share/man/man3/Tcl_RegExpCompile.3
/usr/share/man/man3/Tcl_RegExpExec.3
/usr/share/man/man3/Tcl_RegExpExecObj.3
/usr/share/man/man3/Tcl_RegExpGetInfo.3
/usr/share/man/man3/Tcl_RegExpMatch.3
/usr/share/man/man3/Tcl_RegExpMatchObj.3
/usr/share/man/man3/Tcl_RegExpRange.3
/usr/share/man/man3/Tcl_RegisterChannel.3
/usr/share/man/man3/Tcl_RegisterConfig.3
/usr/share/man/man3/Tcl_RegisterObjType.3
/usr/share/man/man3/Tcl_Release.3
/usr/share/man/man3/Tcl_ResetResult.3
/usr/share/man/man3/Tcl_RestoreInterpState.3
/usr/share/man/man3/Tcl_RestoreResult.3
/usr/share/man/man3/Tcl_SaveInterpState.3
/usr/share/man/man3/Tcl_SaveResult.3
/usr/share/man/man3/Tcl_ScanCountedElement.3
/usr/share/man/man3/Tcl_ScanElement.3
/usr/share/man/man3/Tcl_Seek.3
/usr/share/man/man3/Tcl_ServiceAll.3
/usr/share/man/man3/Tcl_ServiceEvent.3
/usr/share/man/man3/Tcl_ServiceModeHook.3
/usr/share/man/man3/Tcl_SetAssocData.3
/usr/share/man/man3/Tcl_SetBignumObj.3
/usr/share/man/man3/Tcl_SetBooleanObj.3
/usr/share/man/man3/Tcl_SetByteArrayLength.3
/usr/share/man/man3/Tcl_SetByteArrayObj.3
/usr/share/man/man3/Tcl_SetChannelBufferSize.3
/usr/share/man/man3/Tcl_SetChannelError.3
/usr/share/man/man3/Tcl_SetChannelErrorInterp.3
/usr/share/man/man3/Tcl_SetChannelOption.3
/usr/share/man/man3/Tcl_SetCommandInfo.3
/usr/share/man/man3/Tcl_SetCommandInfoFromToken.3
/usr/share/man/man3/Tcl_SetDefaultEncodingDir.3
/usr/share/man/man3/Tcl_SetDoubleObj.3
/usr/share/man/man3/Tcl_SetEncodingSearchPath.3
/usr/share/man/man3/Tcl_SetEnsembleFlags.3
/usr/share/man/man3/Tcl_SetEnsembleMappingDict.3
/usr/share/man/man3/Tcl_SetEnsembleParameterList.3
/usr/share/man/man3/Tcl_SetEnsembleSubcommandList.3
/usr/share/man/man3/Tcl_SetEnsembleUnknownHandler.3
/usr/share/man/man3/Tcl_SetErrno.3
/usr/share/man/man3/Tcl_SetErrorCode.3
/usr/share/man/man3/Tcl_SetErrorCodeVA.3
/usr/share/man/man3/Tcl_SetErrorLine.3
/usr/share/man/man3/Tcl_SetExitProc.3
/usr/share/man/man3/Tcl_SetHashValue.3
/usr/share/man/man3/Tcl_SetIntObj.3
/usr/share/man/man3/Tcl_SetListObj.3
/usr/share/man/man3/Tcl_SetLongObj.3
/usr/share/man/man3/Tcl_SetMainLoop.3
/usr/share/man/man3/Tcl_SetMaxBlockTime.3
/usr/share/man/man3/Tcl_SetNamespaceUnknownHandler.3
/usr/share/man/man3/Tcl_SetNotifier.3
/usr/share/man/man3/Tcl_SetObjErrorCode.3
/usr/share/man/man3/Tcl_SetObjLength.3
/usr/share/man/man3/Tcl_SetObjResult.3
/usr/share/man/man3/Tcl_SetPanicProc.3
/usr/share/man/man3/Tcl_SetRecursionLimit.3
/usr/share/man/man3/Tcl_SetResult.3
/usr/share/man/man3/Tcl_SetReturnOptions.3
/usr/share/man/man3/Tcl_SetServiceMode.3
/usr/share/man/man3/Tcl_SetStartupScript.3
/usr/share/man/man3/Tcl_SetStdChannel.3
/usr/share/man/man3/Tcl_SetStringObj.3
/usr/share/man/man3/Tcl_SetSystemEncoding.3
/usr/share/man/man3/Tcl_SetTimeProc.3
/usr/share/man/man3/Tcl_SetTimer.3
/usr/share/man/man3/Tcl_SetUnicodeObj.3
/usr/share/man/man3/Tcl_SetVar.3
/usr/share/man/man3/Tcl_SetVar2.3
/usr/share/man/man3/Tcl_SetVar2Ex.3
/usr/share/man/man3/Tcl_SetWideIntObj.3
/usr/share/man/man3/Tcl_SignalId.3
/usr/share/man/man3/Tcl_SignalMsg.3
/usr/share/man/man3/Tcl_Sleep.3
/usr/share/man/man3/Tcl_SourceRCFile.3
/usr/share/man/man3/Tcl_SpliceChannel.3
/usr/share/man/man3/Tcl_SplitList.3
/usr/share/man/man3/Tcl_SplitPath.3
/usr/share/man/man3/Tcl_StackChannel.3
/usr/share/man/man3/Tcl_StandardChannels.3
/usr/share/man/man3/Tcl_Stat.3
/usr/share/man/man3/Tcl_StaticPackage.3
/usr/share/man/man3/Tcl_StringCaseMatch.3
/usr/share/man/man3/Tcl_StringMatch.3
/usr/share/man/man3/Tcl_SubstObj.3
/usr/share/man/man3/Tcl_TakeBignumFromObj.3
/usr/share/man/man3/Tcl_Tell.3
/usr/share/man/man3/Tcl_ThreadAlert.3
/usr/share/man/man3/Tcl_ThreadQueueEvent.3
/usr/share/man/man3/Tcl_TraceCommand.3
/usr/share/man/man3/Tcl_TraceVar.3
/usr/share/man/man3/Tcl_TraceVar2.3
/usr/share/man/man3/Tcl_TransferResult.3
/usr/share/man/man3/Tcl_TranslateFileName.3
/usr/share/man/man3/Tcl_TruncateChannel.3
/usr/share/man/man3/Tcl_Ungets.3
/usr/share/man/man3/Tcl_UniChar.3
/usr/share/man/man3/Tcl_UniCharAtIndex.3
/usr/share/man/man3/Tcl_UniCharCaseMatch.3
/usr/share/man/man3/Tcl_UniCharIsAlnum.3
/usr/share/man/man3/Tcl_UniCharIsAlpha.3
/usr/share/man/man3/Tcl_UniCharIsControl.3
/usr/share/man/man3/Tcl_UniCharIsDigit.3
/usr/share/man/man3/Tcl_UniCharIsGraph.3
/usr/share/man/man3/Tcl_UniCharIsLower.3
/usr/share/man/man3/Tcl_UniCharIsPrint.3
/usr/share/man/man3/Tcl_UniCharIsPunct.3
/usr/share/man/man3/Tcl_UniCharIsSpace.3
/usr/share/man/man3/Tcl_UniCharIsUpper.3
/usr/share/man/man3/Tcl_UniCharIsWordChar.3
/usr/share/man/man3/Tcl_UniCharLen.3
/usr/share/man/man3/Tcl_UniCharNcasecmp.3
/usr/share/man/man3/Tcl_UniCharNcmp.3
/usr/share/man/man3/Tcl_UniCharToLower.3
/usr/share/man/man3/Tcl_UniCharToTitle.3
/usr/share/man/man3/Tcl_UniCharToUpper.3
/usr/share/man/man3/Tcl_UniCharToUtf.3
/usr/share/man/man3/Tcl_UniCharToUtfDString.3
/usr/share/man/man3/Tcl_UnlinkVar.3
/usr/share/man/man3/Tcl_UnregisterChannel.3
/usr/share/man/man3/Tcl_UnsetVar.3
/usr/share/man/man3/Tcl_UnsetVar2.3
/usr/share/man/man3/Tcl_UnstackChannel.3
/usr/share/man/man3/Tcl_UntraceCommand.3
/usr/share/man/man3/Tcl_UntraceVar.3
/usr/share/man/man3/Tcl_UntraceVar2.3
/usr/share/man/man3/Tcl_UpVar.3
/usr/share/man/man3/Tcl_UpVar2.3
/usr/share/man/man3/Tcl_UpdateLinkedVar.3
/usr/share/man/man3/Tcl_UtfAtIndex.3
/usr/share/man/man3/Tcl_UtfBackslash.3
/usr/share/man/man3/Tcl_UtfCharComplete.3
/usr/share/man/man3/Tcl_UtfFindFirst.3
/usr/share/man/man3/Tcl_UtfFindLast.3
/usr/share/man/man3/Tcl_UtfNcasecmp.3
/usr/share/man/man3/Tcl_UtfNcmp.3
/usr/share/man/man3/Tcl_UtfNext.3
/usr/share/man/man3/Tcl_UtfPrev.3
/usr/share/man/man3/Tcl_UtfToExternal.3
/usr/share/man/man3/Tcl_UtfToExternalDString.3
/usr/share/man/man3/Tcl_UtfToLower.3
/usr/share/man/man3/Tcl_UtfToTitle.3
/usr/share/man/man3/Tcl_UtfToUniChar.3
/usr/share/man/man3/Tcl_UtfToUniCharDString.3
/usr/share/man/man3/Tcl_UtfToUpper.3
/usr/share/man/man3/Tcl_ValidateAllMemory.3
/usr/share/man/man3/Tcl_VarEval.3
/usr/share/man/man3/Tcl_VarEvalVA.3
/usr/share/man/man3/Tcl_VarTraceInfo.3
/usr/share/man/man3/Tcl_VarTraceInfo2.3
/usr/share/man/man3/Tcl_WaitForEvent.3
/usr/share/man/man3/Tcl_WaitPid.3
/usr/share/man/man3/Tcl_WinTCharToUtf.3
/usr/share/man/man3/Tcl_WinUtfToTChar.3
/usr/share/man/man3/Tcl_Write.3
/usr/share/man/man3/Tcl_WriteChars.3
/usr/share/man/man3/Tcl_WriteObj.3
/usr/share/man/man3/Tcl_WriteRaw.3
/usr/share/man/man3/Tcl_WrongNumArgs.3
/usr/share/man/man3/Tcl_ZlibAdler32.3
/usr/share/man/man3/Tcl_ZlibCRC32.3
/usr/share/man/man3/Tcl_ZlibDeflate.3
/usr/share/man/man3/Tcl_ZlibInflate.3
/usr/share/man/man3/Tcl_ZlibStreamChecksum.3
/usr/share/man/man3/Tcl_ZlibStreamClose.3
/usr/share/man/man3/Tcl_ZlibStreamEof.3
/usr/share/man/man3/Tcl_ZlibStreamGet.3
/usr/share/man/man3/Tcl_ZlibStreamGetCommandName.3
/usr/share/man/man3/Tcl_ZlibStreamInit.3
/usr/share/man/man3/Tcl_ZlibStreamPut.3
/usr/share/man/man3/Tdbc_Init.3
/usr/share/man/man3/attemptckalloc.3
/usr/share/man/man3/attemptckrealloc.3
/usr/share/man/man3/ckalloc.3
/usr/share/man/man3/ckfree.3
/usr/share/man/man3/ckrealloc.3

%files lib
%defattr(-,root,root,-)
/usr/lib64/itcl4.2.0/libitcl4.2.0.so
/usr/lib64/libtcl.so
/usr/lib64/libtcl8.6.so
/usr/lib64/sqlite3.30.1.2/libsqlite3.30.1.2.so
/usr/lib64/tdbc1.1.1/libtdbc1.1.1.so
/usr/lib64/tdbcmysql1.1.1/libtdbcmysql1.1.1.so
/usr/lib64/tdbcodbc1.1.1/libtdbcodbc1.1.1.so
/usr/lib64/tdbcpostgres1.1.1/libtdbcpostgres1.1.1.so
/usr/lib64/thread2.8.5/libthread2.8.5.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/tcl/05c2120a6b8f992414f673c68a562cdf560f46e3
/usr/share/package-licenses/tcl/0694c44c6528f38ba02518028ae540be0daffc82
/usr/share/package-licenses/tcl/44869749a0261aabc6d26adb33554b24f9b017c2
/usr/share/package-licenses/tcl/4cf449426b4a1f7696cb04e69ac100f262f5a715
/usr/share/package-licenses/tcl/4e9de7724f48cff19005312340a7f21ac741b94b
/usr/share/package-licenses/tcl/892b34f7865d90a6f949f50d95e49625a10bc7f0
/usr/share/package-licenses/tcl/af1bb3f2eb2888c6a0cb73a32f12b2f599f9cd1f

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/tclsh.1
/usr/share/man/mann/Tcl.n
/usr/share/man/mann/after.n
/usr/share/man/mann/append.n
/usr/share/man/mann/apply.n
/usr/share/man/mann/argc.n
/usr/share/man/mann/argv.n
/usr/share/man/mann/argv0.n
/usr/share/man/mann/array.n
/usr/share/man/mann/auto_execok.n
/usr/share/man/mann/auto_import.n
/usr/share/man/mann/auto_load.n
/usr/share/man/mann/auto_mkindex.n
/usr/share/man/mann/auto_path.n
/usr/share/man/mann/auto_qualify.n
/usr/share/man/mann/auto_reset.n
/usr/share/man/mann/bgerror.n
/usr/share/man/mann/binary.n
/usr/share/man/mann/body.n
/usr/share/man/mann/break.n
/usr/share/man/mann/case.n
/usr/share/man/mann/catch.n
/usr/share/man/mann/cd.n
/usr/share/man/mann/chan.n
/usr/share/man/mann/class.n
/usr/share/man/mann/clock.n
/usr/share/man/mann/close.n
/usr/share/man/mann/code.n
/usr/share/man/mann/concat.n
/usr/share/man/mann/configbody.n
/usr/share/man/mann/continue.n
/usr/share/man/mann/coroutine.n
/usr/share/man/mann/dde.n
/usr/share/man/mann/delete.n
/usr/share/man/mann/dict.n
/usr/share/man/mann/encoding.n
/usr/share/man/mann/ensemble.n
/usr/share/man/mann/env.n
/usr/share/man/mann/eof.n
/usr/share/man/mann/error.n
/usr/share/man/mann/errorCode.n
/usr/share/man/mann/errorInfo.n
/usr/share/man/mann/eval.n
/usr/share/man/mann/exec.n
/usr/share/man/mann/exit.n
/usr/share/man/mann/expr.n
/usr/share/man/mann/fblocked.n
/usr/share/man/mann/fconfigure.n
/usr/share/man/mann/fcopy.n
/usr/share/man/mann/file.n
/usr/share/man/mann/fileevent.n
/usr/share/man/mann/filename.n
/usr/share/man/mann/find.n
/usr/share/man/mann/flush.n
/usr/share/man/mann/for.n
/usr/share/man/mann/foreach.n
/usr/share/man/mann/format.n
/usr/share/man/mann/gets.n
/usr/share/man/mann/glob.n
/usr/share/man/mann/global.n
/usr/share/man/mann/history.n
/usr/share/man/mann/http.n
/usr/share/man/mann/if.n
/usr/share/man/mann/incr.n
/usr/share/man/mann/info.n
/usr/share/man/mann/interp.n
/usr/share/man/mann/is.n
/usr/share/man/mann/itcl.n
/usr/share/man/mann/itclcomponent.n
/usr/share/man/mann/itcldelegate.n
/usr/share/man/mann/itclextendedclass.n
/usr/share/man/mann/itcloption.n
/usr/share/man/mann/itclvars.n
/usr/share/man/mann/itclwidget.n
/usr/share/man/mann/join.n
/usr/share/man/mann/lappend.n
/usr/share/man/mann/lassign.n
/usr/share/man/mann/library.n
/usr/share/man/mann/lindex.n
/usr/share/man/mann/linsert.n
/usr/share/man/mann/list.n
/usr/share/man/mann/llength.n
/usr/share/man/mann/lmap.n
/usr/share/man/mann/load.n
/usr/share/man/mann/local.n
/usr/share/man/mann/lrange.n
/usr/share/man/mann/lrepeat.n
/usr/share/man/mann/lreplace.n
/usr/share/man/mann/lreverse.n
/usr/share/man/mann/lsearch.n
/usr/share/man/mann/lset.n
/usr/share/man/mann/lsort.n
/usr/share/man/mann/mathfunc.n
/usr/share/man/mann/mathop.n
/usr/share/man/mann/memory.n
/usr/share/man/mann/msgcat.n
/usr/share/man/mann/my.n
/usr/share/man/mann/namespace.n
/usr/share/man/mann/next.n
/usr/share/man/mann/nextto.n
/usr/share/man/mann/oo_class.n
/usr/share/man/mann/oo_copy.n
/usr/share/man/mann/oo_define.n
/usr/share/man/mann/oo_objdefine.n
/usr/share/man/mann/oo_object.n
/usr/share/man/mann/open.n
/usr/share/man/mann/package.n
/usr/share/man/mann/packagens.n
/usr/share/man/mann/parray.n
/usr/share/man/mann/pid.n
/usr/share/man/mann/pkgMkIndex.n
/usr/share/man/mann/pkg_create.n
/usr/share/man/mann/pkg_mkIndex.n
/usr/share/man/mann/platform.n
/usr/share/man/mann/platform_shell.n
/usr/share/man/mann/proc.n
/usr/share/man/mann/puts.n
/usr/share/man/mann/pwd.n
/usr/share/man/mann/re_syntax.n
/usr/share/man/mann/read.n
/usr/share/man/mann/refchan.n
/usr/share/man/mann/regexp.n
/usr/share/man/mann/registry.n
/usr/share/man/mann/regsub.n
/usr/share/man/mann/rename.n
/usr/share/man/mann/return.n
/usr/share/man/mann/safe.n
/usr/share/man/mann/scan.n
/usr/share/man/mann/scope.n
/usr/share/man/mann/seek.n
/usr/share/man/mann/self.n
/usr/share/man/mann/set.n
/usr/share/man/mann/socket.n
/usr/share/man/mann/source.n
/usr/share/man/mann/split.n
/usr/share/man/mann/sqlite3.n
/usr/share/man/mann/string.n
/usr/share/man/mann/subst.n
/usr/share/man/mann/switch.n
/usr/share/man/mann/tailcall.n
/usr/share/man/mann/tcl_endOfWord.n
/usr/share/man/mann/tcl_findLibrary.n
/usr/share/man/mann/tcl_interactive.n
/usr/share/man/mann/tcl_library.n
/usr/share/man/mann/tcl_nonwordchars.n
/usr/share/man/mann/tcl_patchLevel.n
/usr/share/man/mann/tcl_pkgPath.n
/usr/share/man/mann/tcl_platform.n
/usr/share/man/mann/tcl_precision.n
/usr/share/man/mann/tcl_prefix.n
/usr/share/man/mann/tcl_rcFileName.n
/usr/share/man/mann/tcl_startOfNextWord.n
/usr/share/man/mann/tcl_startOfPreviousWord.n
/usr/share/man/mann/tcl_traceCompile.n
/usr/share/man/mann/tcl_traceExec.n
/usr/share/man/mann/tcl_version.n
/usr/share/man/mann/tcl_wordBreakAfter.n
/usr/share/man/mann/tcl_wordBreakBefore.n
/usr/share/man/mann/tcl_wordchars.n
/usr/share/man/mann/tcltest.n
/usr/share/man/mann/tdbc.n
/usr/share/man/mann/tdbc_connection.n
/usr/share/man/mann/tdbc_mapSqlState.n
/usr/share/man/mann/tdbc_mysql.n
/usr/share/man/mann/tdbc_odbc.n
/usr/share/man/mann/tdbc_postgres.n
/usr/share/man/mann/tdbc_resultset.n
/usr/share/man/mann/tdbc_sqlite3.n
/usr/share/man/mann/tdbc_statement.n
/usr/share/man/mann/tdbc_tokenize.n
/usr/share/man/mann/tell.n
/usr/share/man/mann/thread.n
/usr/share/man/mann/throw.n
/usr/share/man/mann/time.n
/usr/share/man/mann/timerate.n
/usr/share/man/mann/tm.n
/usr/share/man/mann/tpool.n
/usr/share/man/mann/trace.n
/usr/share/man/mann/transchan.n
/usr/share/man/mann/try.n
/usr/share/man/mann/tsv.n
/usr/share/man/mann/ttrace.n
/usr/share/man/mann/unknown.n
/usr/share/man/mann/unload.n
/usr/share/man/mann/unset.n
/usr/share/man/mann/update.n
/usr/share/man/mann/uplevel.n
/usr/share/man/mann/upvar.n
/usr/share/man/mann/variable.n
/usr/share/man/mann/vwait.n
/usr/share/man/mann/while.n
/usr/share/man/mann/yield.n
/usr/share/man/mann/yieldto.n
/usr/share/man/mann/zlib.n

%files staticdev
%defattr(-,root,root,-)
/usr/lib64/libtclstub8.6.a
